# Generated by Django 4.0.4 on 2022-05-31 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_viewset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(max_length=500)),
                ('writer', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
