# Generated by Django 4.0.4 on 2022-05-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_viewset', '0002_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='log',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='log',
            name='writer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
