version: '3'

services:
  db:
    image: mysql
    env_file:
      - .env
    volumes:
      - ./docker/data:/var/lib/mysql/data
    environment:
      - MYSQL_TCP_PORT=${MYSQL_TCP_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command:
      - bash
      - -c
      - |
        python manage.py wait_for_db -t 120
        python manage.py migrate
        echo yes | python manage.py collectstatic
        gunicorn DrfProject.wsgi:application --bind 0.0.0.0:8000
    stdin_open: true
    ports:
      - "8000:8000"
    volumes:
      - .:/home/DrfProject
    depends_on:
      - db

  nginx:
    image: nginx:1.21
    restart: always
    volumes:
      - .:/etc/nginx/conf.d
      - ./static:/static
    ports:
      - "80:80"
    depends_on:
      - web
